site_name: Excel Addin
site_description: Documentation for the Excel Addin
site_author: Your Name
site_url: https://therepos.github.io/excel/

theme:
  name: material
  palette:
    primary: black
    accent: white
  font:
    text: Moranga
    code: Fira Code
  features:
    - navigation.tabs
    - navigation.sections

nav:
  - Home: index.md
  - Installation:
      - Guide: index.md
  - FAQ: index.md

plugins:
  - search

extra_css:
  - assets/extra.css

markdown_extensions:
  - pymdownx.superfences
    - toc:
        title: On this page
