name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main  # Replace 'main' with your default branch if different

jobs:
  deploy:
    runs-on: ubuntu-22.04  # Explicitly set the version to avoid warnings

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install MkDocs and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material
          pip install pymdown-extensions

      - name: Verify MkDocs Configuration
        run: |
          echo "Validating mkdocs.yml..."
          mkdocs --version
          cat mkdocs.yml  # Ensure the file exists and is accessible

      - name: Build and Deploy the site
        env:
          CI: true  # Enable CI mode for better error messages
        run: |
          mkdocs gh-deploy --force
